name: publish to Reposilite

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to publish (e.g. v1.2.3)'
        required: true

jobs:
  publish_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.release_tag }}"
          else
            TAG="${GITHUB_REF#refs/*/}"
          fi
          echo "RELEASE_VERSION=$(echo "$TAG" | sed 's/^v//')" >>"$GITHUB_ENV"
          echo "Using tag: $TAG"

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle Build and publish to Reposilite
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            clean
            build
            publish
            -Pversion=${{ env.RELEASE_VERSION }}
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}