name: Publish to Reposilite

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set version
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed "s/^v//")" >> $GITHUB_ENV
          echo "refs: ${{ github.ref }}"

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Gradle build
        run: ./gradlew clean build publish -Pversion=${{ env.RELEASE_VERSION }}

        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}